### ISSUE TITLE
question de performance sur Windows 

### ISSUE THREAD

**Issue by webdevproformation** [LouisBertin/prestashop1.7-docker-lamp#3]
Bonjour à nouveau,

je reviens vers vous au sujet de performance. 
J'utilise PC sur Windows 11 et mon disque dur est formaté en NTFS. 
J'ai bien suivi l'ensemble des étapes d'installation, j'ai juste modifié le volume pour le service web dans docker-compose.yaml

```
services:
    web:
        container_name: ${PROJECT_NAME}_web
        build:
            context: ./conf
            args:
                PHP_VERSION: ${PHP_VERSION}
                NODEJS_VERSION: ${NODEJS_VERSION}
        ports:
            - "8081:80"
        volumes:
            - ./www:/app:delegated
        links:
            - db:db
```

Chaque page du front office et du back prendre au minimum un temps de 14 secondes pour s'afficher ...

J'ai essayé d'activer le cache dans le back office  :
=> les paramètres de cache du back office dans Paramètres avancés > Performances
=> activation du cache smarty
=> activation CCC (Concaténation, Compression et mise en Cache) 
=> mais ce n'est pas mieux 

Est ce que vous utilisez docker sur un PC windows ? 
Est ce que vous avez des suggestions pour améliorer les performances pour afficher des pages ?

sur un XAMPP, chaque page de prestashop prend en moyenne 3 secondes pour être affichée. 

merci beaucoup pour le coup de main !!!
